"""First commit

Revision ID: f2d6a0a15baa
Revises: 
Create Date: 2021-10-26 14:59:07.015550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d6a0a15baa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=45), nullable=False),
    sa.Column('email', sa.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=45), nullable=False),
    sa.Column('text', sa.VARCHAR(length=404), nullable=False),
    sa.Column('idTag', sa.Integer(), nullable=False),
    sa.Column('idOwner', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idOwner'], ['user.id'], ),
    sa.ForeignKeyConstraint(['idTag'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notestatistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Date(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('noteId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['noteId'], ['note.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notestatistics')
    op.drop_table('note')
    op.drop_table('user')
    op.drop_table('tag')
    # ### end Alembic commands ###
